COde Revisions

diff --git a/YTDownloader b/YTDownloader
--- a/YTDownloader
+++ b/YTDownloader
@@ -12,44 +12,53 @@
 #| |_| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |   
 #|____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|   
 # 
+#Simple Program to download Video/Audio(s) from Youtube.
+#
 #Dependencies - youtube-dl, dmenu[promptUser], notify-send
 
 ytDL=/usr/bin/youtube-dl
 notif=/usr/bin/notify-send
-prompt=$HOME/binaries/promptUser
+prompt=$HOME/bin/promptUser
 dest=$HOME/Media/YTDownloads
 url=$(xclip -selection primary -o)
 
-[ -z $url ] && $notif "No Download URL Found" -u "normal" -t 3000 -a "⬇ Downloader" && exit 
-[ ! $(echo $url | grep -E '\.com|\.org|\.net|\.in') ] && $notif "Invalid Url" -u "critical" -t 3000 \
+[ -e $dest ] || mkdir -p $dest
+cd $dest
+
+[ -z "$url" ] && $notif "Nothing to Download" -u "normal" -t 3000 -a "⬇ Downloader" && exit 
+[ ! $(echo $url | grep -E '\.(com|org|net|in)') ] && $notif "Invalid Url." -u "critical" -t 3000 \
 	-a "⬇ Downloader" && exit
 
-if echo $url | grep 'list' > /dev/null; then
-	$($prompt "Download Playlist?")
-	if [ $? -eq 1 ]; then
-		url=$(echo $url | cut -d "&" -f1)
-	fi
-	$($prompt "Download Just Audio?")
-	if [ $? -eq 0 ]; then
-		flags=" -xq --no-warnings --audio-format mp3 --audio-quality 0"
-		format=".mp3"
-	else
-		flags=" -q --no-warnings --format mp4 --audio-format mp3 --audio-quality 0"
-		format=".mp4"
-	fi
-fi
+[ $(echo $url | grep 'list') ] && 
+	options="Download playlist\nDownload current video\nExtract audio from playlist\nExtract audio from current video" ||
+	options="Download current video\nExtract audio from current video" 
 
-title=$($ytDL --get-title $url)
-[ -e $dest ] || mkdir -p $dest
+format=$(echo -e $options | dmenu -i -l 5 -p "Select A Download Format :" | sed -E 's/[ \t]*$//g')
+
+case $format in
+	"Extract audio from playlist") 
+		url=$(echo $url | cut -d "&" -f1-2)
+		flags=" -xq --no-warnings --audio-format mp3 --audio-quality 0";;
+	"Download playlist") 
+		url=$(echo $url | cut -d "&" -f1-2)
+		flags=" -q --no-warnings --format mp4 --audio-format mp3 --audio-quality 0";;
+	"Extract audio from current video")
+		url=$(echo $url | cut -d "&" -f1)
+		flags=" -xq --no-warnings --audio-format mp3 --audio-quality 0";;
+	"Download current video") 
+		url=$(echo $url | cut -d "&" -f1)
+		flags=" -q --no-warnings --format mp4 --audio-format mp3 --audio-quality 0";;
+	*)
+		$notif "Nothing To Download" "Bailing..." -u "normal" -t 3000 -a "⬇ Downloader"
+		exit;;
+esac
+
+title=$($ytDL --get-title $url) 
+[ -z "$title" ] && $notif "Invalid Url" "Bailing..." -u "critical" -t 3000 -a "⬇ Downloader" && exit
 
 $notif "Download Started" "$title" -u "normal" -t 3000 -a "⬇ Downloader"
 
 $ytDL $flags $url
-
-if [ $? -eq 0 ]; then
-	$notif "Download Complete" "$title"  -u "normal" -t 3000 -a "⬇ Downloader"
-	mv -f ./*${format} $dest
-else
+[ $? -eq 0 ] && $notif "Download Complete" "$title"  -u "normal" -t 3000 -a "⬇ Downloader" || 
 	$notif "Download Failed" "$title" -u "critical" -t 3000 -a " ⬇ Downloader"
-fi
 
